"use client";

import Link from "next/link";
import { Bell, Check } from "lucide-react";
import { useCallback, useEffect, useState } from "react";
import { PageHeader } from "@/components/app/page-header";
import { Button } from "@/components/ui/button";
import { ApiError, type NotificationResponse } from "@/lib/api";
import { useAuthenticatedRequest } from "@/lib/use-authenticated-request";

export default function NotificationsPage() {
  const { accessToken, authLoading, requestWithAuth } = useAuthenticatedRequest();
  const [notifications, setNotifications] = useState<NotificationResponse[]>([]);
  const [loading, setLoading] = useState(false);
  const [saving, setSaving] = useState(false);
  const [error, setError] = useState<string | null>(null);

  const loadNotifications = useCallback(async () => {
    if (authLoading) return;
    setLoading(true);
    setError(null);

    try {
      const result = await requestWithAuth<{ data: NotificationResponse[] }>("/notifications?limit=100");

      setNotifications(result.data);
    } catch (caughtError) {
      setError(caughtError instanceof ApiError ? caughtError.message : "Unable to load notifications");
    } finally {
      setLoading(false);
    }
  }, [authLoading, requestWithAuth]);

  useEffect(() => {
    const timeout = window.setTimeout(() => {
      void loadNotifications();
    }, 0);

    return () => window.clearTimeout(timeout);
  }, [loadNotifications]);

  async function markRead(notification: NotificationResponse) {
    setSaving(true);
    setError(null);

    try {
      await requestWithAuth(`/notifications/${notification.id}/read`, { method: "PATCH" });
      await loadNotifications();
    } catch (caughtError) {
      setError(caughtError instanceof ApiError ? caughtError.message : "Unable to update notification");
    } finally {
      setSaving(false);
    }
  }

  if (!authLoading && !accessToken) {
    return (
      <>
        <PageHeader eyebrow="Notifications" title="Operational alerts" description="Sign in to load tenant-scoped notifications." icon={Bell} />
        <div className="p-4 sm:p-6">
          <div className="rounded-lg border border-border bg-card p-4 text-sm text-muted-foreground">
            Notifications require an authenticated session. <Link href="/login" className="font-medium text-primary hover:underline">Sign in</Link>
          </div>
        </div>
      </>
    );
  }

  return (
    <>
      <PageHeader eyebrow="Notifications" title="Operational alerts for stock, orders, and shipments" description="Live alerts generated by backend workflows." icon={Bell} />
      <div className="p-4 sm:p-6">
        <div className="mx-auto max-w-4xl space-y-3">
          {error ? <div className="rounded-lg border border-destructive/30 bg-destructive/10 p-3 text-sm text-destructive">{error}</div> : null}
          {loading ? <div className="rounded-lg border border-border bg-card p-4 text-sm text-muted-foreground">Loading notifications...</div> : null}
          {notifications.length === 0 ? (
            <div className="rounded-lg border border-border bg-card p-6 text-center text-sm text-muted-foreground">No notifications yet.</div>
          ) : notifications.map((notification) => (
            <article key={notification.id} className="rounded-lg border border-border bg-card p-4 shadow-sm">
              <div className="flex flex-col gap-3 sm:flex-row sm:items-start sm:justify-between">
                <div className="min-w-0">
                  <div className="flex flex-wrap items-center gap-2">
                    <h2 className="text-sm font-semibold text-foreground">{notification.title}</h2>
                    <span className="rounded-full bg-muted px-2 py-1 text-xs text-muted-foreground">
                      {notification.readAt ? "Read" : "Unread"}
                    </span>
                  </div>
                  <p className="mt-2 text-sm leading-6 text-muted-foreground">{notification.body}</p>
                  <p className="mt-2 text-xs text-muted-foreground">{new Date(notification.createdAt).toLocaleString()}</p>
                </div>
                <Button type="button" variant="outline" size="sm" disabled={saving || Boolean(notification.readAt)} onClick={() => void markRead(notification)}>
                  <Check className="mr-2 size-4" aria-hidden="true" />Mark read
                </Button>
              </div>
            </article>
          ))}
        </div>
      </div>
    </>
  );
}
