import type {
  ChartPoint,
  InventoryItem,
  Kpi,
  Notification,
  Order,
  Product,
  Shipment,
  TimelineEvent,
  Warehouse,
  WarehouseBin,
} from "@/lib/app-types";

export const dashboardKpis: Kpi[] = [
  {
    label: "Total orders",
    value: "1,284",
    change: "+12.4% vs last month",
    tone: "positive",
  },
  {
    label: "Inventory value",
    value: "$842.6k",
    change: "Across 4 warehouses",
    tone: "neutral",
  },
  {
    label: "Open shipments",
    value: "126",
    change: "18 need dispatch review",
    tone: "warning",
  },
  {
    label: "On-time delivery",
    value: "94.2%",
    change: "+2.1% this week",
    tone: "positive",
  },
];

export const products: Product[] = [
  {
    id: "prd-101",
    name: "Trail Runner Sole Kit",
    sku: "BS-SOLE-118",
    category: "Footwear Parts",
    status: "Active",
    stock: 420,
    reorderPoint: 90,
    warehouse: "North Dock",
    value: 12600,
  },
  {
    id: "prd-102",
    name: "All Weather Upper",
    sku: "BS-UPR-204",
    category: "Footwear Parts",
    status: "Low stock",
    stock: 38,
    reorderPoint: 80,
    warehouse: "Central Hub",
    value: 7600,
  },
  {
    id: "prd-103",
    name: "Retail Box Medium",
    sku: "BS-PKG-332",
    category: "Packaging",
    status: "Active",
    stock: 3200,
    reorderPoint: 700,
    warehouse: "South Annex",
    value: 4480,
  },
  {
    id: "prd-104",
    name: "Carbon Laces Pack",
    sku: "BS-LCE-554",
    category: "Accessories",
    status: "Draft",
    stock: 0,
    reorderPoint: 250,
    warehouse: "North Dock",
    value: 0,
  },
  {
    id: "prd-105",
    name: "Return Inspection Tag",
    sku: "BS-TAG-771",
    category: "Operations",
    status: "Active",
    stock: 860,
    reorderPoint: 150,
    warehouse: "West Returns",
    value: 1290,
  },
];

export const inventoryItems: InventoryItem[] = [
  {
    id: "inv-1001",
    product: "Trail Runner Sole Kit",
    sku: "BS-SOLE-118",
    warehouse: "North Dock",
    bin: "A-04-02",
    available: 420,
    reserved: 64,
    reorderPoint: 90,
    risk: "Healthy",
    lastMovement: "Reserved 24 units for SO-1048",
  },
  {
    id: "inv-1002",
    product: "All Weather Upper",
    sku: "BS-UPR-204",
    warehouse: "Central Hub",
    bin: "C-11-08",
    available: 38,
    reserved: 14,
    reorderPoint: 80,
    risk: "Low",
    lastMovement: "Received 18 units from supplier",
  },
  {
    id: "inv-1003",
    product: "Retail Box Medium",
    sku: "BS-PKG-332",
    warehouse: "South Annex",
    bin: "S-02-12",
    available: 3200,
    reserved: 780,
    reorderPoint: 700,
    risk: "Healthy",
    lastMovement: "Transferred 500 units to North Dock",
  },
  {
    id: "inv-1004",
    product: "Return Inspection Tag",
    sku: "BS-TAG-771",
    warehouse: "West Returns",
    bin: "R-01-03",
    available: 860,
    reserved: 40,
    reorderPoint: 150,
    risk: "Watch",
    lastMovement: "Adjusted cycle count by -12",
  },
];

export const warehouses: Warehouse[] = [
  {
    id: "wh-north",
    name: "North Dock",
    location: "Dallas, TX",
    manager: "Maya Chen",
    utilization: 78,
    activeBins: 142,
    totalBins: 180,
    dailyMoves: 312,
  },
  {
    id: "wh-central",
    name: "Central Hub",
    location: "Kansas City, MO",
    manager: "Owen Patel",
    utilization: 86,
    activeBins: 218,
    totalBins: 254,
    dailyMoves: 451,
  },
  {
    id: "wh-south",
    name: "South Annex",
    location: "Atlanta, GA",
    manager: "Nora Ellis",
    utilization: 64,
    activeBins: 96,
    totalBins: 150,
    dailyMoves: 188,
  },
  {
    id: "wh-west",
    name: "West Returns",
    location: "Reno, NV",
    manager: "Luis Moreno",
    utilization: 52,
    activeBins: 57,
    totalBins: 110,
    dailyMoves: 79,
  },
];

export const warehouseBins: WarehouseBin[] = [
  {
    code: "A-04-02",
    zone: "Picking",
    product: "Trail Runner Sole Kit",
    quantity: 420,
    status: "Reserved",
  },
  {
    code: "C-11-08",
    zone: "Inbound",
    product: "All Weather Upper",
    quantity: 38,
    status: "Open",
  },
  {
    code: "S-02-12",
    zone: "Bulk",
    product: "Retail Box Medium",
    quantity: 3200,
    status: "Full",
  },
  {
    code: "R-01-03",
    zone: "Returns",
    product: "Return Inspection Tag",
    quantity: 860,
    status: "Open",
  },
];

export const orders: Order[] = [
  {
    id: "SO-1048",
    customer: "Summit Retail Co.",
    status: "Reserved",
    items: 12,
    total: 18420,
    warehouse: "North Dock",
    owner: "Ari Lane",
    dueDate: "May 31, 2026",
  },
  {
    id: "SO-1049",
    customer: "MarketFleet",
    status: "Packed",
    items: 8,
    total: 11280,
    warehouse: "Central Hub",
    owner: "Maya Chen",
    dueDate: "Jun 1, 2026",
  },
  {
    id: "SO-1050",
    customer: "Blue Ridge Supply",
    status: "Shipped",
    items: 19,
    total: 24600,
    warehouse: "South Annex",
    owner: "Owen Patel",
    dueDate: "Jun 2, 2026",
  },
  {
    id: "SO-1051",
    customer: "Northstar Outlet",
    status: "Draft",
    items: 4,
    total: 3920,
    warehouse: "Central Hub",
    owner: "Nora Ellis",
    dueDate: "Jun 5, 2026",
  },
  {
    id: "SO-1052",
    customer: "Runner's Corner",
    status: "Delivered",
    items: 15,
    total: 17240,
    warehouse: "North Dock",
    owner: "Luis Moreno",
    dueDate: "May 27, 2026",
  },
];

export const shipments: Shipment[] = [
  {
    id: "SHP-7781",
    orderId: "SO-1049",
    carrier: "RoadLine",
    status: "Assigned",
    destination: "Denver, CO",
    eta: "Jun 1, 2026",
    progress: 38,
  },
  {
    id: "SHP-7782",
    orderId: "SO-1050",
    carrier: "FreightOne",
    status: "In transit",
    destination: "Charlotte, NC",
    eta: "Jun 2, 2026",
    progress: 62,
  },
  {
    id: "SHP-7783",
    orderId: "SO-1052",
    carrier: "NorthTrail",
    status: "Delivered",
    destination: "Portland, OR",
    eta: "May 27, 2026",
    progress: 100,
  },
  {
    id: "SHP-7784",
    orderId: "SO-1048",
    carrier: "MetroShip",
    status: "Pending",
    destination: "Austin, TX",
    eta: "May 31, 2026",
    progress: 14,
  },
];

export const notifications: Notification[] = [
  {
    id: "note-01",
    title: "All Weather Upper below reorder point",
    description: "Central Hub has 38 available units against an 80 unit reorder point.",
    type: "Low stock",
    priority: "High",
    time: "12 min ago",
  },
  {
    id: "note-02",
    title: "SHP-7782 reached regional depot",
    description: "FreightOne updated the tracking timeline for order SO-1050.",
    type: "Shipment",
    priority: "Medium",
    time: "34 min ago",
  },
  {
    id: "note-03",
    title: "SO-1048 is ready for allocation review",
    description: "Reservation is complete and packing can begin after manager approval.",
    type: "Order",
    priority: "Medium",
    time: "1 hr ago",
  },
  {
    id: "note-04",
    title: "Nightly report generation completed",
    description: "Operational snapshots are ready for dashboard review.",
    type: "System",
    priority: "Low",
    time: "3 hr ago",
  },
];

export const stockMovements: TimelineEvent[] = [
  {
    id: "move-01",
    title: "Reserved inventory",
    description: "24 Trail Runner Sole Kits reserved for SO-1048.",
    time: "09:42",
    status: "Reserve",
  },
  {
    id: "move-02",
    title: "Inbound stock received",
    description: "18 All Weather Uppers received at Central Hub.",
    time: "10:18",
    status: "Inbound",
  },
  {
    id: "move-03",
    title: "Cycle count adjustment",
    description: "Return Inspection Tag adjusted by -12 after bin count.",
    time: "11:05",
    status: "Adjust",
  },
  {
    id: "move-04",
    title: "Warehouse transfer",
    description: "500 Retail Box Medium units moved to North Dock.",
    time: "13:24",
    status: "Transfer",
  },
];

export const shipmentTimeline: TimelineEvent[] = [
  {
    id: "ship-01",
    title: "Order packed",
    description: "SO-1049 packed and waiting at Central Hub outbound lane.",
    time: "08:20",
    status: "Packed",
  },
  {
    id: "ship-02",
    title: "Carrier assigned",
    description: "RoadLine assigned to SHP-7781 with pickup window confirmed.",
    time: "09:10",
    status: "Assigned",
  },
  {
    id: "ship-03",
    title: "Depot scan",
    description: "SHP-7782 reached the Charlotte regional depot.",
    time: "11:55",
    status: "In transit",
  },
  {
    id: "ship-04",
    title: "Delivery confirmed",
    description: "SHP-7783 delivered with signed proof of delivery.",
    time: "14:40",
    status: "Delivered",
  },
];

export const salesChartData: ChartPoint[] = [
  { name: "Jan", orders: 168, revenue: 142 },
  { name: "Feb", orders: 190, revenue: 151 },
  { name: "Mar", orders: 224, revenue: 178 },
  { name: "Apr", orders: 238, revenue: 192 },
  { name: "May", orders: 284, revenue: 214 },
  { name: "Jun", orders: 306, revenue: 238 },
];

export const inventoryTrendData: ChartPoint[] = [
  { name: "Jan", inventory: 690 },
  { name: "Feb", inventory: 718 },
  { name: "Mar", inventory: 702 },
  { name: "Apr", inventory: 764 },
  { name: "May", inventory: 842 },
  { name: "Jun", inventory: 856 },
];

export const shipmentPerformanceData: ChartPoint[] = [
  { name: "Mon", shipped: 42, delayed: 4 },
  { name: "Tue", shipped: 58, delayed: 6 },
  { name: "Wed", shipped: 51, delayed: 5 },
  { name: "Thu", shipped: 66, delayed: 3 },
  { name: "Fri", shipped: 74, delayed: 7 },
];

export const warehouseActivityData: ChartPoint[] = [
  { name: "North", moves: 312 },
  { name: "Central", moves: 451 },
  { name: "South", moves: 188 },
  { name: "West", moves: 79 },
];
